package uz.devops.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DoctorWorkScheduleAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDoctorWorkScheduleAllPropertiesEquals(DoctorWorkSchedule expected, DoctorWorkSchedule actual) {
        assertDoctorWorkScheduleAutoGeneratedPropertiesEquals(expected, actual);
        assertDoctorWorkScheduleAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDoctorWorkScheduleAllUpdatablePropertiesEquals(DoctorWorkSchedule expected, DoctorWorkSchedule actual) {
        assertDoctorWorkScheduleUpdatableFieldsEquals(expected, actual);
        assertDoctorWorkScheduleUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDoctorWorkScheduleAutoGeneratedPropertiesEquals(DoctorWorkSchedule expected, DoctorWorkSchedule actual) {
        assertThat(expected)
            .as("Verify DoctorWorkSchedule auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDoctorWorkScheduleUpdatableFieldsEquals(DoctorWorkSchedule expected, DoctorWorkSchedule actual) {
        // empty method

    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDoctorWorkScheduleUpdatableRelationshipsEquals(DoctorWorkSchedule expected, DoctorWorkSchedule actual) {
        // empty method
    }
}
