package uz.devops.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MedicalHistoryAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMedicalHistoryAllPropertiesEquals(MedicalHistory expected, MedicalHistory actual) {
        assertMedicalHistoryAutoGeneratedPropertiesEquals(expected, actual);
        assertMedicalHistoryAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMedicalHistoryAllUpdatablePropertiesEquals(MedicalHistory expected, MedicalHistory actual) {
        assertMedicalHistoryUpdatableFieldsEquals(expected, actual);
        assertMedicalHistoryUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMedicalHistoryAutoGeneratedPropertiesEquals(MedicalHistory expected, MedicalHistory actual) {
        assertThat(expected)
            .as("Verify MedicalHistory auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMedicalHistoryUpdatableFieldsEquals(MedicalHistory expected, MedicalHistory actual) {
        assertThat(expected)
            .as("Verify MedicalHistory relevant properties")
            .satisfies(e -> assertThat(e.getCreatedDate()).as("check createdDate").isEqualTo(actual.getCreatedDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMedicalHistoryUpdatableRelationshipsEquals(MedicalHistory expected, MedicalHistory actual) {
        // empty method
    }
}
