package uz.devops.domain.enumeration;

/**
 * The Specialization enumeration.
 */
public enum Specialization {
    GENERAL_PRACTITIONER,
    PEDIATRICIAN,
    SURGEON,
    CARDIOLOGIST,
    GYNECOLOGIST,
    DERMATOLOGIST,
    NEUROLOGIST,
    GASTROENTEROLOGIST,
    ENDOCRINOLOGIST,
    UROLOGIST,
    OPHTHALMOLOGIST,
    ENT_SPECIALIST,
    PSYCHIATRIST,
    REHABILITATION_SPECIALIST,
    ONCOLOGIST,
    ANESTHESIOLOGIST,
    GERIATRICIAN,
    PULMONOLOGIST,
    SPORTS_MEDICINE_SPECIALIST,
    MEDICAL_GENETICIST,
}
